name: Run pytest on Pull Request

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'

    - name: Install dependencies
      run: |
        pip install poetry==1.7.0
        poetry install

    - name: Run pytest
      run: poetry run pytest
